### ISSUE TITLE
Why on earth qdrant.UpsertPoints.Wait is a pointer of boolean type?

### ISSUE THREAD

**Issue by hungpham2411** [qdrant/go-client#59]
Every time I need to assign a value to UpsertPoints.Wait, I have to use an anonymous function.  
```
upsertPoints := &qdrant.UpsertPoints{}
...
upsertPoints.Wait = func() *bool {
         v := true
         return &v
 }()
```
Is that for saving a bit of memory or something else?

**Comment by Anush008** [comment]
Hey.
This is auto-generated based on the proto definitions at https://github.com/qdrant/qdrant/tree/master/lib/api/src/grpc.

I believe this is done to distinguish between true, false and null values. Since if it was a `bool`, it would default to `false`. Wheres a `*bool` defaults to `nil`.

Also, you can do,

```go
wait := true
upsertPoints := &qdrant.UpsertPoints{
	Wait: &wait
}
```

OR

```go
upsertPoints := &qdrant.UpsertPoints{
	Wait: qdrant.PtrOf(true)
}
```

**Comment by hungpham2411** [comment]
> Hey. This is auto-generated based on the proto definitions at https://github.com/qdrant/qdrant/tree/master/lib/api/src/grpc/proto.
> 
> I believe this is done to distinguish between true, false and null values. Since if it was a `bool`, it would default to `false`in Go. Whereas a `*bool` defaults to `nil`.

Thanks. You made the point.
